# ==========================
# CloudCart SonarQube Config
# ==========================

sonar.projectKey=cloudcart

sonar.projectName=CloudCart

sonar.projectVersion=1.0

sonar.sources=app/backend

sonar.sourceEncoding=UTF-8

# Ignore Python cache files
sonar.exclusions=**/__pycache__/**,**/*.pyc

# Python version
sonar.python.version=3.9
