apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloudcart-backend

  template:
    metadata:
      labels:
        app: cloudcart-backend

    spec:
      containers:
      - name: backend
        image: cloudcart-backend:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5000
